-- Config/Items.luau
return {
    { name="Common Brainrot",    chance=1/2,         rarity="Common",    colorHex="CCCCCC", emoji="⚪" },
    { name="Uncommon Brainrot",  chance=1/10,        rarity="Uncommon",  colorHex="1EFF00", emoji="🟢" },
    { name="Rare Brainrot",      chance=1/100,       rarity="Rare",      colorHex="0070DD", emoji="🔵" },
    { name="Epic Brainrot",      chance=1/1000,      rarity="Epic",      colorHex="A335EE", emoji="🟣" },
    { name="Legendary Brainrot", chance=1/2048,      rarity="Legendary", colorHex="FF8000", emoji="🟠" },
    { name="Mythic Brainrot",    chance=1/100000,    rarity="Mythic",    colorHex="E6CC80", emoji="🌟" },
    { name="SECRET Brainrot",    chance=1/200000000, rarity="SECRET",    colorHex="FF0000", emoji="💀" },
}